plugin: aws_ec2
regions:
  - us-west-1
filters:
  instance-state-name: running
  tag:Name: "JuanWordpress-*"

keyed_groups:
  - key: tags.role
    prefix: role

hostnames:
  - tag:Name
  - public-ip-address

compose: 
  ansible_host: public_ip_address

