---
- name: Detect package manager family
  set_fact:
    pkg_mgr_family: "{{ ansible_facts['os_family'] | lower }}"

- name: Update apt cache (Debian)
  apt: 
   update_cache: yes
  when: pkg_mgr_family == 'debian'

- name: Install packages (Debian)
  apt:
    name:
      - apache2
      - php
      - php-mysql
    state: present
    update_cache: yes
  when: pkg_mgr_family == 'debian'

- name: Install packages (CentOS)
  package:
    name:
      - httpd
      - php
      - php-mysqlnd
    state: present
  when: pkg_mgr_family != 'debian'

- name: Ensure apache/httpd enabled & started (Debian)
  service:
    name: apache2
    state: started
    enabled: true
  when: pkg_mgr_family == 'debian'
  notify: Restart webserver

- name: Ensure httpd enabled & started (Centos)
  service:
    name: httpd
    state: started
    enabled: true
  when: pkg_mgr_family != 'debian'
  notify: Restart webserver

- name: Ensure document root exists
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Deploy custom index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'


