---
- name: Detect package manager family
  set_fact:
    pkg_mgr_family: "{{ ansible_facts['os_family'] | lower }}"

- name: Update apt cache (Debian)
  apt: 
   update_cache: yes
  when: pkg_mgr_family == 'debian'

- name: Install packages (Debian)
  apt:
    name:
      - apache2
      - php
      - php-mysql
    state: present
    update_cache: yes
  when: pkg_mgr_family == 'debian'

- name: Install packages (CentOS)
  package:
    name:
      - httpd
      - php
      - php-mysqlnd
    state: present
  when: pkg_mgr_family != 'debian'

- name: Ensure apache/httpd enabled & started (Debian)
  service:
    name: apache2
    state: started
    enabled: true
  when: pkg_mgr_family == 'debian'
  notify: Restart webserver

- name: Ensure httpd enabled & started (Centos)
  service:
    name: httpd
    state: started
    enabled: true
  when: pkg_mgr_family != 'debian'
  notify: Restart webserver

- name: Download WordPress tarball
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    mode: '0644'
    force: yes

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes

- name: Ensure ownership of web root
  file: 
    path: /var/www/html
    state: directory
    owner: "{{ 'www-data' if pkg_mgr_family == 'debian' else 'apache' }}"
    group: "{{ 'www-data' if pkg_mgr_family == 'debian' else 'apache' }}"
    recurse: yes

- name: Create wp-config.php from template
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: "{{ 'www-data' if pkg_mgr_family == 'debian' else 'apache' }}"
    group: "{{ 'www-data' if pkg_mgr_family == 'debian' else 'apache' }}"
    mode: '0640'

