name: Terraform + Ansible deploy

on:
  workflow_dispatch:
    inputs:
        action:
          description: 'Selecciona apply o destroy'
          required: true
          default: 'apply'

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'apply' }}
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install ansible boto3 botocore

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform init
      run: terraform init
      working-directory: ./Terraform

    - name: Terraform apply
      id: tf_apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        TF_VAR_db_password: ${{ secrets.RDS_PASSWORD }}
      run: terraform apply -auto-approve
      working-directory: ./Terraform

    - name: Capture Terraform outputs
      id: tf_outputs
      run: |
        terraform output -json > terraform_outputs.json
        mv terraform_outputs.json ../ansible/
        mkdir -p /home/runner/.ssh
        chmod 700 /home/runner/.ssh
        cp Juan-key.pem /home/runner/.ssh/Juan-key.pem
        chmod 600 /home/runner/.ssh/Juan-key.pem
      working-directory: ./Terraform

    - name: Check terraform_outputs.json
      run: ls -l ./ansible/terraform_outputs.json
  
    - name: Run Ansible playbook
      run: |
        ansible-playbook site.yml
      working-directory: ./ansible

  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'destroy'
  
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
  
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
  
    - name: Terraform init
      run: terraform init
      working-directory: ./Terraform
  
    - name: Terraform destroy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: terraform destroy -auto-approve
      working-directory: ./Terraform
